### ISSUE TITLE
Completion for \textbf and \emph

### ISSUE THREAD

**Issue by manuel-uberti** [alexeyr/company-auctex#10]
Hi, first of all thanks for this great backend for company-mode.

When writing a TeX file, I cannot auto-complete \textbf and \emph because they are not shown in the candidates list. 

Is there a way to add them to the available candidates?

I know AUCTeX provides them via keybindings, so I completely understand if you don't plan to add them.

**Comment by alexeyr** [comment]
I'll look into it when I have time.
