### ISSUE TITLE
sections?

### ISSUE THREAD

**Issue by izahn** [alexeyr/company-auctex#5]
I don't seem to be getting completions for section/subsection etc. Is that expected?

**Comment by alexeyr** [comment]
Yes, it isn't implemented currently. Pull request welcome :) Otherwise, I'll implement it when I have time, but I rarely do.

**Comment by pronobis** [comment]
PR https://github.com/alexeyr/company-auctex/pull/7

**Comment by alexeyr** [comment]
Merged.
